name: Proptriz Merge

# Controls when the workflow will execute
on:
  # Triggers the workflow when build successfully completes
  workflow_run:
    workflows: ["Proptriz Build"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge:
    name: ðŸ”€ Merge
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev' }}

    # The sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge dev to staging
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "dev"
          destination_branch: "staging"
          pr_title: "Automated PR to merge dev to staging"
          pr_body: ":robot: Automated PR from **dev** to **staging**; see commits."
          pr_label: "auto-pr"
